FT50_JOURNALS = frozenset(name.lower().strip() for name in [
    "Academy of Management Journal",
    "Academy of Management Review",
    "Accounting, Organizations and Society",
    "Administrative Science Quarterly",
    "American Economic Review",
    "American Journal of Sociology",
    "American Political Science Review",
    "American Sociological Review",
    "Contemporary Accounting Research",
    "Econometrica",
    "Economic Journal",
    "Entrepreneurship Theory and Practice",
    "Harvard Business Review",
    "Human Relations",
    "Human Resource Management",
    "Industrial and Labor Relations Review",
    "Information Systems Research",
    "Journal of Accounting and Economics",
    "Journal of Accounting Research",
    "Journal of Applied Psychology",
    "Journal of Business Ethics",
    "Journal of Business Venturing",
    "Journal of Consumer Psychology",
    "Journal of Consumer Research",
    "Journal of Finance",
    "Journal of Financial and Quantitative Analysis",
    "Journal of Financial Economics",
    "Journal of International Business Studies",
    "Journal of Management",
    "Journal of Management Information Systems",
    "Journal of Management Studies",
    "Journal of Marketing",
    "Journal of Marketing Research",
    "Journal of Operations Management",
    "Journal of Political Economy",
    "Journal of the Academy of Marketing Science",
    "Management Science",
    "Marketing Science",
    "MIS Quarterly",
    "Operations Research",
    "Organization Science",
    "Organization Studies",
    "Organizational Behavior and Human Decision Processes",
    "Production and Operations Management",
    "Quarterly Journal of Economics",
    "Research Policy",
    "Review of Economic Studies",
    "Review of Financial Studies",
    "Strategic Management Journal",
    "The Accounting Review",
])

ABS_4_JOURNALS = frozenset(name.lower().strip() for name in [
    # 4* (starred)
    "Academy of Management Journal",
    "Academy of Management Review",
    "Administrative Science Quarterly",
    "American Economic Review",
    "Econometrica",
    "Journal of Finance",
    "Journal of Financial Economics",
    "Journal of Marketing",
    "Management Science",
    "MIS Quarterly",
    "Operations Research",
    "Organization Science",
    "Quarterly Journal of Economics",
    "Review of Economic Studies",
    "Review of Financial Studies",
    "Strategic Management Journal",
    "The Accounting Review",
    # 4
    "Accounting, Organizations and Society",
    "American Journal of Sociology",
    "Contemporary Accounting Research",
    "Human Relations",
    "Information Systems Research",
    "Journal of Accounting and Economics",
    "Journal of Accounting Research",
    "Journal of Applied Psychology",
    "Journal of Business Venturing",
    "Journal of Consumer Research",
    "Journal of Financial and Quantitative Analysis",
    "Journal of International Business Studies",
    "Journal of Management",
    "Journal of Management Studies",
    "Journal of Marketing Research",
    "Journal of Operations Management",
    "Journal of Political Economy",
    "Organizational Behavior and Human Decision Processes",
    "Production and Operations Management",
    "Research Policy",
])

BEHAV_ECON_JOURNALS = frozenset(name.lower().strip() for name in [
    "Quarterly Journal of Economics",
    "Journal of Political Economy",
    "Econometrica",
    "Review of Economic Studies",
    "Journal of Finance",
    "Journal of Financial Economics",
    "Management Science",
    "American Economic Review",
    "Review of Financial Studies",
    "Journal of Consumer Research",
    "Psychological Science",
    "Journal of Behavioral Decision Making",
])
